name: smart_time_manager_mobile
description: Smart Time Manager mobile controller app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: web/icons/Icon-512.png
  remove_alpha_ios: true
  adaptive_icon_background: "#0D9488"
  adaptive_icon_foreground: web/icons/Icon-512.png

flutter:
  uses-material-design: true
